-- add given dept details (dname, loc) into the dept table.
-- deptno should be autogenerated -- MAX(deptno) + 10.

DROP PROCEDURE IF EXISTS sp_add_dept;

DELIMITER $$

CREATE PROCEDURE sp_add_dept(v_dname CHAR(40), v_loc CHAR(40))
BEGIN
	DECLARE v_deptno INT;
	SELECT MAX(deptno) INTO v_deptno FROM dept;
	INSERT INTO dept(deptno, dname, loc) VALUES (v_deptno + 10, v_dname, v_loc);
END;
$$

DELIMITER ;

-- mysql> SOURCE D:/path/to/demo07.sql;
-- mysql> CALL sp_add_dept('TRAINING', 'PUNE');
-- mysql> SELECT * FROM dept;
-- mysql> CALL sp_add_dept('PRODUCUTION', 'MUMBAI');
-- mysql> SELECT * FROM dept;
